// Core API <-> Worker internal RPC contract. Replaces the earlier HTTP+JSON
// /internal/* endpoints on both sides (see .claude/memory/mynexus_grpc_migration.md)
// with gRPC over a single persistent HTTP/2 connection per direction: fewer
// TCP/TLS handshakes than one-shot HTTP/1.1 requests, binary protobuf instead
// of JSON marshal/unmarshal, and native support for the chat streaming case.
//
// Two independent services because the relationship is bidirectional:
// Core API calls Worker to trigger ingestion/search/chat, and Worker calls
// Core API back to report task progress and to run Postgres-only keyword
// search (see .claude/memory/mynexus_keyword_search_gin.md). Each side is
// simultaneously a gRPC client (of the other service) and a gRPC server (of
// its own service).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: mynexus.proto

package mynexuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_mynexus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{0}
}

type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Chapters      []*Chapter             `protobuf:"bytes,3,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_mynexus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{1}
}

func (x *SummarizeRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SummarizeRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *SummarizeRequest) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type SummarizeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeAck) Reset() {
	*x = SummarizeAck{}
	mi := &file_mynexus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeAck) ProtoMessage() {}

func (x *SummarizeAck) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeAck.ProtoReflect.Descriptor instead.
func (*SummarizeAck) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{2}
}

func (x *SummarizeAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type IngestRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BookId           string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	FilePath         string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	OriginalFilename string                 `protobuf:"bytes,4,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_mynexus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{3}
}

func (x *IngestRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *IngestRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *IngestRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *IngestRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

type IngestAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_mynexus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{4}
}

func (x *IngestAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	BookIds        []string               `protobuf:"bytes,2,rep,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	TopK           int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	ScoreThreshold float64                `protobuf:"fixed64,4,opt,name=score_threshold,json=scoreThreshold,proto3" json:"score_threshold,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_mynexus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetBookIds() []string {
	if x != nil {
		return x.BookIds
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetScoreThreshold() float64 {
	if x != nil {
		return x.ScoreThreshold
	}
	return 0
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,3,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	TokenCount    int32                  `protobuf:"varint,6,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	Score         float64                `protobuf:"fixed64,7,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_mynexus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResult) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SearchResult) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *SearchResult) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *SearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchResult) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *SearchResult) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *SearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_mynexus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_mynexus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	BookIds       []string               `protobuf:"bytes,2,rep,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_mynexus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{9}
}

func (x *ChatRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetBookIds() []string {
	if x != nil {
		return x.BookIds
	}
	return nil
}

func (x *ChatRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type Citation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	BookId        string                 `protobuf:"bytes,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_mynexus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{10}
}

func (x *Citation) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *Citation) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *Citation) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Citation) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Citation) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CitationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Citation            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CitationList) Reset() {
	*x = CitationList{}
	mi := &file_mynexus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CitationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitationList) ProtoMessage() {}

func (x *CitationList) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitationList.ProtoReflect.Descriptor instead.
func (*CitationList) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{11}
}

func (x *CitationList) GetItems() []*Citation {
	if x != nil {
		return x.Items
	}
	return nil
}

// One chunk of a streamed chat reply: either an answer-text delta, or (the
// final message in the stream) the full citation list.
type ChatChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatChunk_Delta
	//	*ChatChunk_Citations
	Payload       isChatChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_mynexus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{12}
}

func (x *ChatChunk) GetPayload() isChatChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatChunk) GetDelta() string {
	if x != nil {
		if x, ok := x.Payload.(*ChatChunk_Delta); ok {
			return x.Delta
		}
	}
	return ""
}

func (x *ChatChunk) GetCitations() *CitationList {
	if x != nil {
		if x, ok := x.Payload.(*ChatChunk_Citations); ok {
			return x.Citations
		}
	}
	return nil
}

type isChatChunk_Payload interface {
	isChatChunk_Payload()
}

type ChatChunk_Delta struct {
	Delta string `protobuf:"bytes,1,opt,name=delta,proto3,oneof"`
}

type ChatChunk_Citations struct {
	Citations *CitationList `protobuf:"bytes,2,opt,name=citations,proto3,oneof"`
}

func (*ChatChunk_Delta) isChatChunk_Payload() {}

func (*ChatChunk_Citations) isChatChunk_Payload() {}

type ProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_mynexus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{13}
}

func (x *ProgressRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProgressRequest) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressRequest) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *ProgressRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_mynexus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{14}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type BookMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookMeta) Reset() {
	*x = BookMeta{}
	mi := &file_mynexus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookMeta) ProtoMessage() {}

func (x *BookMeta) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookMeta.ProtoReflect.Descriptor instead.
func (*BookMeta) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{15}
}

func (x *BookMeta) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookMeta) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookMeta) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type Chapter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_mynexus_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{16}
}

func (x *Chapter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chapter) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Chapter) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Chapter) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	TokenCount    int32                  `protobuf:"varint,5,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	VectorId      string                 `protobuf:"bytes,6,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_mynexus_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{17}
}

func (x *Chunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chunk) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chunk) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Chunk) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *Chunk) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Book          *BookMeta              `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_mynexus_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{18}
}

func (x *MetadataRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MetadataRequest) GetBook() *BookMeta {
	if x != nil {
		return x.Book
	}
	return nil
}

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Book          *BookMeta              `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	Chapters      []*Chapter             `protobuf:"bytes,3,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Chunks        []*Chunk               `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_mynexus_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{19}
}

func (x *CompleteRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CompleteRequest) GetBook() *BookMeta {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *CompleteRequest) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *CompleteRequest) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type FailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_mynexus_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{20}
}

func (x *FailRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *FailRequest) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type ChapterSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ChapterId     string                 `protobuf:"bytes,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterSummaryRequest) Reset() {
	*x = ChapterSummaryRequest{}
	mi := &file_mynexus_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterSummaryRequest) ProtoMessage() {}

func (x *ChapterSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterSummaryRequest.ProtoReflect.Descriptor instead.
func (*ChapterSummaryRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{21}
}

func (x *ChapterSummaryRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ChapterSummaryRequest) GetChapterId() string {
	if x != nil {
		return x.ChapterId
	}
	return ""
}

func (x *ChapterSummaryRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type BookSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSummaryRequest) Reset() {
	*x = BookSummaryRequest{}
	mi := &file_mynexus_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSummaryRequest) ProtoMessage() {}

func (x *BookSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSummaryRequest.ProtoReflect.Descriptor instead.
func (*BookSummaryRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{22}
}

func (x *BookSummaryRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *BookSummaryRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *BookSummaryRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type KeywordSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	BookIds       []string               `protobuf:"bytes,2,rep,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordSearchRequest) Reset() {
	*x = KeywordSearchRequest{}
	mi := &file_mynexus_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordSearchRequest) ProtoMessage() {}

func (x *KeywordSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordSearchRequest.ProtoReflect.Descriptor instead.
func (*KeywordSearchRequest) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{23}
}

func (x *KeywordSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *KeywordSearchRequest) GetBookIds() []string {
	if x != nil {
		return x.BookIds
	}
	return nil
}

func (x *KeywordSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type KeywordSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordSearchResult) Reset() {
	*x = KeywordSearchResult{}
	mi := &file_mynexus_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordSearchResult) ProtoMessage() {}

func (x *KeywordSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordSearchResult.ProtoReflect.Descriptor instead.
func (*KeywordSearchResult) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{24}
}

func (x *KeywordSearchResult) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *KeywordSearchResult) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *KeywordSearchResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type KeywordSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*KeywordSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeywordSearchResponse) Reset() {
	*x = KeywordSearchResponse{}
	mi := &file_mynexus_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeywordSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordSearchResponse) ProtoMessage() {}

func (x *KeywordSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mynexus_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordSearchResponse.ProtoReflect.Descriptor instead.
func (*KeywordSearchResponse) Descriptor() ([]byte, []int) {
	return file_mynexus_proto_rawDescGZIP(), []int{25}
}

func (x *KeywordSearchResponse) GetResults() []*KeywordSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_mynexus_proto protoreflect.FileDescriptor

const file_mynexus_proto_rawDesc = "" +
	"\n" +
	"\rmynexus.proto\x12\amynexus\"\x11\n" +
	"\x0fShutdownRequest\"r\n" +
	"\x10SummarizeRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12,\n" +
	"\bchapters\x18\x03 \x03(\v2\x10.mynexus.ChapterR\bchapters\"*\n" +
	"\fSummarizeAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x8b\x01\n" +
	"\rIngestRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12+\n" +
	"\x11original_filename\x18\x04 \x01(\tR\x10originalFilename\"'\n" +
	"\tIngestAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"~\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\bbook_ids\x18\x02 \x03(\tR\abookIds\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12'\n" +
	"\x0fscore_threshold\x18\x04 \x01(\x01R\x0escoreThreshold\"\xce\x01\n" +
	"\fSearchResult\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x03 \x01(\tR\tchapterId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12\x1f\n" +
	"\vtoken_count\x18\x06 \x01(\x05R\n" +
	"tokenCount\x12\x14\n" +
	"\x05score\x18\a \x01(\x01R\x05score\"A\n" +
	"\x0eSearchResponse\x12/\n" +
	"\aresults\x18\x01 \x03(\v2\x15.mynexus.SearchResultR\aresults\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"o\n" +
	"\vChatRequest\x120\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.mynexus.ChatMessageR\bmessages\x12\x19\n" +
	"\bbook_ids\x18\x02 \x03(\tR\abookIds\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"\x8d\x01\n" +
	"\bCitation\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\tR\tchapterId\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"7\n" +
	"\fCitationList\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.mynexus.CitationR\x05items\"e\n" +
	"\tChatChunk\x12\x16\n" +
	"\x05delta\x18\x01 \x01(\tH\x00R\x05delta\x125\n" +
	"\tcitations\x18\x02 \x01(\v2\x15.mynexus.CitationListH\x00R\tcitationsB\t\n" +
	"\apayload\"v\n" +
	"\x0fProgressRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"T\n" +
	"\bBookMeta\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"~\n" +
	"\aChapter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"\xaa\x01\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\tR\tchapterId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\x12\x1f\n" +
	"\vtoken_count\x18\x05 \x01(\x05R\n" +
	"tokenCount\x12\x1b\n" +
	"\tvector_id\x18\x06 \x01(\tR\bvectorId\"Q\n" +
	"\x0fMetadataRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x04book\x18\x02 \x01(\v2\x11.mynexus.BookMetaR\x04book\"\xa7\x01\n" +
	"\x0fCompleteRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x04book\x18\x02 \x01(\v2\x11.mynexus.BookMetaR\x04book\x12,\n" +
	"\bchapters\x18\x03 \x03(\v2\x10.mynexus.ChapterR\bchapters\x12&\n" +
	"\x06chunks\x18\x04 \x03(\v2\x0e.mynexus.ChunkR\x06chunks\"C\n" +
	"\vFailRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"i\n" +
	"\x15ChapterSummaryRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\tR\tchapterId\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"`\n" +
	"\x12BookSummaryRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"\\\n" +
	"\x14KeywordSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x19\n" +
	"\bbook_ids\x18\x02 \x03(\tR\abookIds\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"_\n" +
	"\x13KeywordSearchResult\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\"O\n" +
	"\x15KeywordSearchResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.mynexus.KeywordSearchResultR\aresults2\xb5\x02\n" +
	"\rWorkerService\x12;\n" +
	"\rTriggerIngest\x12\x16.mynexus.IngestRequest\x1a\x12.mynexus.IngestAck\x129\n" +
	"\x06Search\x12\x16.mynexus.SearchRequest\x1a\x17.mynexus.SearchResponse\x122\n" +
	"\x04Chat\x12\x14.mynexus.ChatRequest\x1a\x12.mynexus.ChatChunk0\x01\x122\n" +
	"\bShutdown\x12\x18.mynexus.ShutdownRequest\x1a\f.mynexus.Ack\x12D\n" +
	"\x10TriggerSummarize\x12\x19.mynexus.SummarizeRequest\x1a\x15.mynexus.SummarizeAck2\xc6\x03\n" +
	"\x0eCoreApiService\x128\n" +
	"\x0eReportProgress\x12\x18.mynexus.ProgressRequest\x1a\f.mynexus.Ack\x128\n" +
	"\x0eReportMetadata\x12\x18.mynexus.MetadataRequest\x1a\f.mynexus.Ack\x128\n" +
	"\x0eReportComplete\x12\x18.mynexus.CompleteRequest\x1a\f.mynexus.Ack\x120\n" +
	"\n" +
	"ReportFail\x12\x14.mynexus.FailRequest\x1a\f.mynexus.Ack\x12D\n" +
	"\x14ReportChapterSummary\x12\x1e.mynexus.ChapterSummaryRequest\x1a\f.mynexus.Ack\x12>\n" +
	"\x11ReportBookSummary\x12\x1b.mynexus.BookSummaryRequest\x1a\f.mynexus.Ack\x12N\n" +
	"\rKeywordSearch\x12\x1d.mynexus.KeywordSearchRequest\x1a\x1e.mynexus.KeywordSearchResponseB-Z+mynexus/core-api/internal/grpcapi/mynexuspbb\x06proto3"

var (
	file_mynexus_proto_rawDescOnce sync.Once
	file_mynexus_proto_rawDescData []byte
)

func file_mynexus_proto_rawDescGZIP() []byte {
	file_mynexus_proto_rawDescOnce.Do(func() {
		file_mynexus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mynexus_proto_rawDesc), len(file_mynexus_proto_rawDesc)))
	})
	return file_mynexus_proto_rawDescData
}

var file_mynexus_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_mynexus_proto_goTypes = []any{
	(*ShutdownRequest)(nil),       // 0: mynexus.ShutdownRequest
	(*SummarizeRequest)(nil),      // 1: mynexus.SummarizeRequest
	(*SummarizeAck)(nil),          // 2: mynexus.SummarizeAck
	(*IngestRequest)(nil),         // 3: mynexus.IngestRequest
	(*IngestAck)(nil),             // 4: mynexus.IngestAck
	(*SearchRequest)(nil),         // 5: mynexus.SearchRequest
	(*SearchResult)(nil),          // 6: mynexus.SearchResult
	(*SearchResponse)(nil),        // 7: mynexus.SearchResponse
	(*ChatMessage)(nil),           // 8: mynexus.ChatMessage
	(*ChatRequest)(nil),           // 9: mynexus.ChatRequest
	(*Citation)(nil),              // 10: mynexus.Citation
	(*CitationList)(nil),          // 11: mynexus.CitationList
	(*ChatChunk)(nil),             // 12: mynexus.ChatChunk
	(*ProgressRequest)(nil),       // 13: mynexus.ProgressRequest
	(*Ack)(nil),                   // 14: mynexus.Ack
	(*BookMeta)(nil),              // 15: mynexus.BookMeta
	(*Chapter)(nil),               // 16: mynexus.Chapter
	(*Chunk)(nil),                 // 17: mynexus.Chunk
	(*MetadataRequest)(nil),       // 18: mynexus.MetadataRequest
	(*CompleteRequest)(nil),       // 19: mynexus.CompleteRequest
	(*FailRequest)(nil),           // 20: mynexus.FailRequest
	(*ChapterSummaryRequest)(nil), // 21: mynexus.ChapterSummaryRequest
	(*BookSummaryRequest)(nil),    // 22: mynexus.BookSummaryRequest
	(*KeywordSearchRequest)(nil),  // 23: mynexus.KeywordSearchRequest
	(*KeywordSearchResult)(nil),   // 24: mynexus.KeywordSearchResult
	(*KeywordSearchResponse)(nil), // 25: mynexus.KeywordSearchResponse
}
var file_mynexus_proto_depIdxs = []int32{
	16, // 0: mynexus.SummarizeRequest.chapters:type_name -> mynexus.Chapter
	6,  // 1: mynexus.SearchResponse.results:type_name -> mynexus.SearchResult
	8,  // 2: mynexus.ChatRequest.messages:type_name -> mynexus.ChatMessage
	10, // 3: mynexus.CitationList.items:type_name -> mynexus.Citation
	11, // 4: mynexus.ChatChunk.citations:type_name -> mynexus.CitationList
	15, // 5: mynexus.MetadataRequest.book:type_name -> mynexus.BookMeta
	15, // 6: mynexus.CompleteRequest.book:type_name -> mynexus.BookMeta
	16, // 7: mynexus.CompleteRequest.chapters:type_name -> mynexus.Chapter
	17, // 8: mynexus.CompleteRequest.chunks:type_name -> mynexus.Chunk
	24, // 9: mynexus.KeywordSearchResponse.results:type_name -> mynexus.KeywordSearchResult
	3,  // 10: mynexus.WorkerService.TriggerIngest:input_type -> mynexus.IngestRequest
	5,  // 11: mynexus.WorkerService.Search:input_type -> mynexus.SearchRequest
	9,  // 12: mynexus.WorkerService.Chat:input_type -> mynexus.ChatRequest
	0,  // 13: mynexus.WorkerService.Shutdown:input_type -> mynexus.ShutdownRequest
	1,  // 14: mynexus.WorkerService.TriggerSummarize:input_type -> mynexus.SummarizeRequest
	13, // 15: mynexus.CoreApiService.ReportProgress:input_type -> mynexus.ProgressRequest
	18, // 16: mynexus.CoreApiService.ReportMetadata:input_type -> mynexus.MetadataRequest
	19, // 17: mynexus.CoreApiService.ReportComplete:input_type -> mynexus.CompleteRequest
	20, // 18: mynexus.CoreApiService.ReportFail:input_type -> mynexus.FailRequest
	21, // 19: mynexus.CoreApiService.ReportChapterSummary:input_type -> mynexus.ChapterSummaryRequest
	22, // 20: mynexus.CoreApiService.ReportBookSummary:input_type -> mynexus.BookSummaryRequest
	23, // 21: mynexus.CoreApiService.KeywordSearch:input_type -> mynexus.KeywordSearchRequest
	4,  // 22: mynexus.WorkerService.TriggerIngest:output_type -> mynexus.IngestAck
	7,  // 23: mynexus.WorkerService.Search:output_type -> mynexus.SearchResponse
	12, // 24: mynexus.WorkerService.Chat:output_type -> mynexus.ChatChunk
	14, // 25: mynexus.WorkerService.Shutdown:output_type -> mynexus.Ack
	2,  // 26: mynexus.WorkerService.TriggerSummarize:output_type -> mynexus.SummarizeAck
	14, // 27: mynexus.CoreApiService.ReportProgress:output_type -> mynexus.Ack
	14, // 28: mynexus.CoreApiService.ReportMetadata:output_type -> mynexus.Ack
	14, // 29: mynexus.CoreApiService.ReportComplete:output_type -> mynexus.Ack
	14, // 30: mynexus.CoreApiService.ReportFail:output_type -> mynexus.Ack
	14, // 31: mynexus.CoreApiService.ReportChapterSummary:output_type -> mynexus.Ack
	14, // 32: mynexus.CoreApiService.ReportBookSummary:output_type -> mynexus.Ack
	25, // 33: mynexus.CoreApiService.KeywordSearch:output_type -> mynexus.KeywordSearchResponse
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_mynexus_proto_init() }
func file_mynexus_proto_init() {
	if File_mynexus_proto != nil {
		return
	}
	file_mynexus_proto_msgTypes[12].OneofWrappers = []any{
		(*ChatChunk_Delta)(nil),
		(*ChatChunk_Citations)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mynexus_proto_rawDesc), len(file_mynexus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mynexus_proto_goTypes,
		DependencyIndexes: file_mynexus_proto_depIdxs,
		MessageInfos:      file_mynexus_proto_msgTypes,
	}.Build()
	File_mynexus_proto = out.File
	file_mynexus_proto_goTypes = nil
	file_mynexus_proto_depIdxs = nil
}
