// Core API <-> Worker internal RPC contract. Replaces the earlier HTTP+JSON
// /internal/* endpoints on both sides (see .claude/memory/mynexus_grpc_migration.md)
// with gRPC over a single persistent HTTP/2 connection per direction: fewer
// TCP/TLS handshakes than one-shot HTTP/1.1 requests, binary protobuf instead
// of JSON marshal/unmarshal, and native support for the chat streaming case.
//
// Two independent services because the relationship is bidirectional:
// Core API calls Worker to trigger ingestion/search/chat, and Worker calls
// Core API back to report task progress and to run Postgres-only keyword
// search (see .claude/memory/mynexus_keyword_search_gin.md). Each side is
// simultaneously a gRPC client (of the other service) and a gRPC server (of
// its own service).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.1
// source: mynexus.proto

package mynexuspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerService_TriggerIngest_FullMethodName = "/mynexus.WorkerService/TriggerIngest"
	WorkerService_Search_FullMethodName        = "/mynexus.WorkerService/Search"
	WorkerService_Chat_FullMethodName          = "/mynexus.WorkerService/Chat"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerServiceClient interface {
	// Starts parsing file_path in the background and returns immediately;
	// Worker reports progress/completion/failure back via CoreApiService.
	TriggerIngest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestAck, error)
	// Synchronous hybrid (vector + keyword) search.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Streaming RAG chat: yields answer deltas, then exactly one citations
	// message as the final element.
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) TriggerIngest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestAck)
	err := c.cc.Invoke(ctx, WorkerService_TriggerIngest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, WorkerService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_ChatClient = grpc.ServerStreamingClient[ChatChunk]

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
type WorkerServiceServer interface {
	// Starts parsing file_path in the background and returns immediately;
	// Worker reports progress/completion/failure back via CoreApiService.
	TriggerIngest(context.Context, *IngestRequest) (*IngestAck, error)
	// Synchronous hybrid (vector + keyword) search.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Streaming RAG chat: yields answer deltas, then exactly one citations
	// message as the final element.
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) TriggerIngest(context.Context, *IngestRequest) (*IngestAck, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerIngest not implemented")
}
func (UnimplementedWorkerServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedWorkerServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatChunk]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_TriggerIngest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).TriggerIngest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_TriggerIngest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).TriggerIngest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_ChatServer = grpc.ServerStreamingServer[ChatChunk]

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mynexus.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerIngest",
			Handler:    _WorkerService_TriggerIngest_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _WorkerService_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _WorkerService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mynexus.proto",
}

const (
	CoreApiService_ReportProgress_FullMethodName = "/mynexus.CoreApiService/ReportProgress"
	CoreApiService_ReportComplete_FullMethodName = "/mynexus.CoreApiService/ReportComplete"
	CoreApiService_ReportFail_FullMethodName     = "/mynexus.CoreApiService/ReportFail"
	CoreApiService_KeywordSearch_FullMethodName  = "/mynexus.CoreApiService/KeywordSearch"
)

// CoreApiServiceClient is the client API for CoreApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreApiServiceClient interface {
	ReportProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*Ack, error)
	ReportComplete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*Ack, error)
	ReportFail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*Ack, error)
	// Postgres-only GIN-indexed keyword search (see
	// .claude/memory/mynexus_keyword_search_gin.md) — Worker calls this
	// read-only endpoint instead of building a BM25 index in-process when
	// storage.database == "postgres"; unimplemented (NOT_FOUND) on sqlite.
	KeywordSearch(ctx context.Context, in *KeywordSearchRequest, opts ...grpc.CallOption) (*KeywordSearchResponse, error)
}

type coreApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreApiServiceClient(cc grpc.ClientConnInterface) CoreApiServiceClient {
	return &coreApiServiceClient{cc}
}

func (c *coreApiServiceClient) ReportProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CoreApiService_ReportProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreApiServiceClient) ReportComplete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CoreApiService_ReportComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreApiServiceClient) ReportFail(ctx context.Context, in *FailRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, CoreApiService_ReportFail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreApiServiceClient) KeywordSearch(ctx context.Context, in *KeywordSearchRequest, opts ...grpc.CallOption) (*KeywordSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeywordSearchResponse)
	err := c.cc.Invoke(ctx, CoreApiService_KeywordSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreApiServiceServer is the server API for CoreApiService service.
// All implementations must embed UnimplementedCoreApiServiceServer
// for forward compatibility.
type CoreApiServiceServer interface {
	ReportProgress(context.Context, *ProgressRequest) (*Ack, error)
	ReportComplete(context.Context, *CompleteRequest) (*Ack, error)
	ReportFail(context.Context, *FailRequest) (*Ack, error)
	// Postgres-only GIN-indexed keyword search (see
	// .claude/memory/mynexus_keyword_search_gin.md) — Worker calls this
	// read-only endpoint instead of building a BM25 index in-process when
	// storage.database == "postgres"; unimplemented (NOT_FOUND) on sqlite.
	KeywordSearch(context.Context, *KeywordSearchRequest) (*KeywordSearchResponse, error)
	mustEmbedUnimplementedCoreApiServiceServer()
}

// UnimplementedCoreApiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreApiServiceServer struct{}

func (UnimplementedCoreApiServiceServer) ReportProgress(context.Context, *ProgressRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedCoreApiServiceServer) ReportComplete(context.Context, *CompleteRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportComplete not implemented")
}
func (UnimplementedCoreApiServiceServer) ReportFail(context.Context, *FailRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportFail not implemented")
}
func (UnimplementedCoreApiServiceServer) KeywordSearch(context.Context, *KeywordSearchRequest) (*KeywordSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeywordSearch not implemented")
}
func (UnimplementedCoreApiServiceServer) mustEmbedUnimplementedCoreApiServiceServer() {}
func (UnimplementedCoreApiServiceServer) testEmbeddedByValue()                        {}

// UnsafeCoreApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreApiServiceServer will
// result in compilation errors.
type UnsafeCoreApiServiceServer interface {
	mustEmbedUnimplementedCoreApiServiceServer()
}

func RegisterCoreApiServiceServer(s grpc.ServiceRegistrar, srv CoreApiServiceServer) {
	// If the following call panics, it indicates UnimplementedCoreApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreApiService_ServiceDesc, srv)
}

func _CoreApiService_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreApiServiceServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreApiService_ReportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreApiServiceServer).ReportProgress(ctx, req.(*ProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreApiService_ReportComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreApiServiceServer).ReportComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreApiService_ReportComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreApiServiceServer).ReportComplete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreApiService_ReportFail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreApiServiceServer).ReportFail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreApiService_ReportFail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreApiServiceServer).ReportFail(ctx, req.(*FailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreApiService_KeywordSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeywordSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreApiServiceServer).KeywordSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreApiService_KeywordSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreApiServiceServer).KeywordSearch(ctx, req.(*KeywordSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreApiService_ServiceDesc is the grpc.ServiceDesc for CoreApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mynexus.CoreApiService",
	HandlerType: (*CoreApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportProgress",
			Handler:    _CoreApiService_ReportProgress_Handler,
		},
		{
			MethodName: "ReportComplete",
			Handler:    _CoreApiService_ReportComplete_Handler,
		},
		{
			MethodName: "ReportFail",
			Handler:    _CoreApiService_ReportFail_Handler,
		},
		{
			MethodName: "KeywordSearch",
			Handler:    _CoreApiService_KeywordSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mynexus.proto",
}
