# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mynexus_pb2 as mynexus__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mynexus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """---- WorkerService: implemented by Worker, called by Core API ----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerIngest = channel.unary_unary(
                '/mynexus.WorkerService/TriggerIngest',
                request_serializer=mynexus__pb2.IngestRequest.SerializeToString,
                response_deserializer=mynexus__pb2.IngestAck.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/mynexus.WorkerService/Search',
                request_serializer=mynexus__pb2.SearchRequest.SerializeToString,
                response_deserializer=mynexus__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/mynexus.WorkerService/Chat',
                request_serializer=mynexus__pb2.ChatRequest.SerializeToString,
                response_deserializer=mynexus__pb2.ChatChunk.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """---- WorkerService: implemented by Worker, called by Core API ----

    """

    def TriggerIngest(self, request, context):
        """Starts parsing file_path in the background and returns immediately;
        Worker reports progress/completion/failure back via CoreApiService.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Synchronous hybrid (vector + keyword) search.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Streaming RAG chat: yields answer deltas, then exactly one citations
        message as the final element.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerIngest': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerIngest,
                    request_deserializer=mynexus__pb2.IngestRequest.FromString,
                    response_serializer=mynexus__pb2.IngestAck.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=mynexus__pb2.SearchRequest.FromString,
                    response_serializer=mynexus__pb2.SearchResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=mynexus__pb2.ChatRequest.FromString,
                    response_serializer=mynexus__pb2.ChatChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mynexus.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mynexus.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """---- WorkerService: implemented by Worker, called by Core API ----

    """

    @staticmethod
    def TriggerIngest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.WorkerService/TriggerIngest',
            mynexus__pb2.IngestRequest.SerializeToString,
            mynexus__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.WorkerService/Search',
            mynexus__pb2.SearchRequest.SerializeToString,
            mynexus__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mynexus.WorkerService/Chat',
            mynexus__pb2.ChatRequest.SerializeToString,
            mynexus__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoreApiServiceStub(object):
    """---- CoreApiService: implemented by Core API, called by Worker ----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportProgress = channel.unary_unary(
                '/mynexus.CoreApiService/ReportProgress',
                request_serializer=mynexus__pb2.ProgressRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportComplete = channel.unary_unary(
                '/mynexus.CoreApiService/ReportComplete',
                request_serializer=mynexus__pb2.CompleteRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportFail = channel.unary_unary(
                '/mynexus.CoreApiService/ReportFail',
                request_serializer=mynexus__pb2.FailRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.KeywordSearch = channel.unary_unary(
                '/mynexus.CoreApiService/KeywordSearch',
                request_serializer=mynexus__pb2.KeywordSearchRequest.SerializeToString,
                response_deserializer=mynexus__pb2.KeywordSearchResponse.FromString,
                _registered_method=True)


class CoreApiServiceServicer(object):
    """---- CoreApiService: implemented by Core API, called by Worker ----

    """

    def ReportProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportFail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeywordSearch(self, request, context):
        """Postgres-only GIN-indexed keyword search (see
        .claude/memory/mynexus_keyword_search_gin.md) — Worker calls this
        read-only endpoint instead of building a BM25 index in-process when
        storage.database == "postgres"; unimplemented (NOT_FOUND) on sqlite.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=mynexus__pb2.ProgressRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'ReportComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportComplete,
                    request_deserializer=mynexus__pb2.CompleteRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'ReportFail': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportFail,
                    request_deserializer=mynexus__pb2.FailRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'KeywordSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.KeywordSearch,
                    request_deserializer=mynexus__pb2.KeywordSearchRequest.FromString,
                    response_serializer=mynexus__pb2.KeywordSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mynexus.CoreApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mynexus.CoreApiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreApiService(object):
    """---- CoreApiService: implemented by Core API, called by Worker ----

    """

    @staticmethod
    def ReportProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/ReportProgress',
            mynexus__pb2.ProgressRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/ReportComplete',
            mynexus__pb2.CompleteRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportFail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/ReportFail',
            mynexus__pb2.FailRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KeywordSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/KeywordSearch',
            mynexus__pb2.KeywordSearchRequest.SerializeToString,
            mynexus__pb2.KeywordSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
