# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mynexus_pb2 as mynexus__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mynexus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """---- WorkerService: implemented by Worker, called by Core API ----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerIngest = channel.unary_unary(
                '/mynexus.WorkerService/TriggerIngest',
                request_serializer=mynexus__pb2.IngestRequest.SerializeToString,
                response_deserializer=mynexus__pb2.IngestAck.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/mynexus.WorkerService/Search',
                request_serializer=mynexus__pb2.SearchRequest.SerializeToString,
                response_deserializer=mynexus__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/mynexus.WorkerService/Chat',
                request_serializer=mynexus__pb2.ChatRequest.SerializeToString,
                response_deserializer=mynexus__pb2.ChatChunk.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/mynexus.WorkerService/Shutdown',
                request_serializer=mynexus__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.TriggerSummarize = channel.unary_unary(
                '/mynexus.WorkerService/TriggerSummarize',
                request_serializer=mynexus__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=mynexus__pb2.SummarizeAck.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """---- WorkerService: implemented by Worker, called by Core API ----

    """

    def TriggerIngest(self, request, context):
        """Starts parsing file_path in the background and returns immediately;
        Worker reports progress/completion/failure back via CoreApiService.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Synchronous hybrid (vector + keyword) search.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Streaming RAG chat: yields answer deltas, then exactly one citations
        message as the final element.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Acknowledges then exits the process shortly after replying — Core API
        calls this after rewriting config.yaml from the system settings page, so
        Worker restarts and picks up new embedding/llm/splitter config. Relies on
        an external supervisor (Docker Compose's `restart: unless-stopped`) to
        bring the process back up; in a bare `python3 server.py` dev run nothing
        restarts it automatically. Best-effort: Core API ignores failures here
        (Worker being unreachable already means it isn't running to restart).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerSummarize(self, request, context):
        """Starts a map-reduce summarization run in the background and returns
        immediately, mirroring TriggerIngest: Worker never touches Core API's
        database directly (see .claude/memory/mynexus_m2_decisions.md), so the
        chapters to summarize are sent in the request rather than fetched by
        Worker itself. Map: each chapter is summarized individually and reported
        back (and persisted) as soon as it's done via ReportChapterSummary, so
        partial progress survives a mid-run crash. Reduce: once every chapter
        has a summary, they're combined into one whole-book summary, reported
        via ReportBookSummary — which also marks the task complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerIngest': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerIngest,
                    request_deserializer=mynexus__pb2.IngestRequest.FromString,
                    response_serializer=mynexus__pb2.IngestAck.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=mynexus__pb2.SearchRequest.FromString,
                    response_serializer=mynexus__pb2.SearchResponse.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=mynexus__pb2.ChatRequest.FromString,
                    response_serializer=mynexus__pb2.ChatChunk.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=mynexus__pb2.ShutdownRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'TriggerSummarize': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerSummarize,
                    request_deserializer=mynexus__pb2.SummarizeRequest.FromString,
                    response_serializer=mynexus__pb2.SummarizeAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mynexus.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mynexus.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """---- WorkerService: implemented by Worker, called by Core API ----

    """

    @staticmethod
    def TriggerIngest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.WorkerService/TriggerIngest',
            mynexus__pb2.IngestRequest.SerializeToString,
            mynexus__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.WorkerService/Search',
            mynexus__pb2.SearchRequest.SerializeToString,
            mynexus__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mynexus.WorkerService/Chat',
            mynexus__pb2.ChatRequest.SerializeToString,
            mynexus__pb2.ChatChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.WorkerService/Shutdown',
            mynexus__pb2.ShutdownRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerSummarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.WorkerService/TriggerSummarize',
            mynexus__pb2.SummarizeRequest.SerializeToString,
            mynexus__pb2.SummarizeAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoreApiServiceStub(object):
    """---- CoreApiService: implemented by Core API, called by Worker ----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportProgress = channel.unary_unary(
                '/mynexus.CoreApiService/ReportProgress',
                request_serializer=mynexus__pb2.ProgressRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportMetadata = channel.unary_unary(
                '/mynexus.CoreApiService/ReportMetadata',
                request_serializer=mynexus__pb2.MetadataRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportComplete = channel.unary_unary(
                '/mynexus.CoreApiService/ReportComplete',
                request_serializer=mynexus__pb2.CompleteRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportFail = channel.unary_unary(
                '/mynexus.CoreApiService/ReportFail',
                request_serializer=mynexus__pb2.FailRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportChapterSummary = channel.unary_unary(
                '/mynexus.CoreApiService/ReportChapterSummary',
                request_serializer=mynexus__pb2.ChapterSummaryRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportBookSummary = channel.unary_unary(
                '/mynexus.CoreApiService/ReportBookSummary',
                request_serializer=mynexus__pb2.BookSummaryRequest.SerializeToString,
                response_deserializer=mynexus__pb2.Ack.FromString,
                _registered_method=True)
        self.KeywordSearch = channel.unary_unary(
                '/mynexus.CoreApiService/KeywordSearch',
                request_serializer=mynexus__pb2.KeywordSearchRequest.SerializeToString,
                response_deserializer=mynexus__pb2.KeywordSearchResponse.FromString,
                _registered_method=True)


class CoreApiServiceServicer(object):
    """---- CoreApiService: implemented by Core API, called by Worker ----

    """

    def ReportProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMetadata(self, request, context):
        """Persists title/author/language as soon as parsing succeeds, well before
        splitting/embedding finish — so a book's metadata is visible in the UI
        even if a later stage (e.g. the embedding API call) fails. ReportComplete
        still sends BookMeta too, as a harmless overwrite with the same values,
        to keep the "everything happens in ReportComplete on success" case simple.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportFail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportChapterSummary(self, request, context):
        """Map step of summarization: persists one chapter's summary immediately
        (see TriggerSummarize). Does not touch the task's status/progress or the
        book's ingest status — ReportProgress covers progress, and a book being
        "ready" (already ingested) is independent of whether a later
        summarization run is in flight or has failed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportBookSummary(self, request, context):
        """Reduce step: persists the whole-book summary and marks the summarize
        task completed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeywordSearch(self, request, context):
        """Postgres-only GIN-indexed keyword search (see
        .claude/memory/mynexus_keyword_search_gin.md) — Worker calls this
        read-only endpoint instead of building a BM25 index in-process when
        storage.database == "postgres"; unimplemented (NOT_FOUND) on sqlite.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=mynexus__pb2.ProgressRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'ReportMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetadata,
                    request_deserializer=mynexus__pb2.MetadataRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'ReportComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportComplete,
                    request_deserializer=mynexus__pb2.CompleteRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'ReportFail': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportFail,
                    request_deserializer=mynexus__pb2.FailRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'ReportChapterSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportChapterSummary,
                    request_deserializer=mynexus__pb2.ChapterSummaryRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'ReportBookSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportBookSummary,
                    request_deserializer=mynexus__pb2.BookSummaryRequest.FromString,
                    response_serializer=mynexus__pb2.Ack.SerializeToString,
            ),
            'KeywordSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.KeywordSearch,
                    request_deserializer=mynexus__pb2.KeywordSearchRequest.FromString,
                    response_serializer=mynexus__pb2.KeywordSearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mynexus.CoreApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mynexus.CoreApiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoreApiService(object):
    """---- CoreApiService: implemented by Core API, called by Worker ----

    """

    @staticmethod
    def ReportProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/ReportProgress',
            mynexus__pb2.ProgressRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/ReportMetadata',
            mynexus__pb2.MetadataRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/ReportComplete',
            mynexus__pb2.CompleteRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportFail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/ReportFail',
            mynexus__pb2.FailRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportChapterSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/ReportChapterSummary',
            mynexus__pb2.ChapterSummaryRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportBookSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/ReportBookSummary',
            mynexus__pb2.BookSummaryRequest.SerializeToString,
            mynexus__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KeywordSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mynexus.CoreApiService/KeywordSearch',
            mynexus__pb2.KeywordSearchRequest.SerializeToString,
            mynexus__pb2.KeywordSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
